spring:
  profiles:
    active: dev
---
spring:
#  profiles: dev
  cloud:
    config:
      profile: dev
server:
  port: 8085
---
spring:
  profiles: test
  cloud:
    bootstrap:
      enabled: false
    config:
      uri: http://localhost:9999
      name: webclient
      profile: test
---
spring:
  profiles: prod
  cloud:
    bootstrap:
      enabled: false
    config:
      uri: http://localhost:9999
      name: webclient
      profile: prod

